services:
  postgres:
    image: 'postgres:18'
    container_name: db_hidratai
    environment:
      - 'POSTGRES_DB=hidratai'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - '5432:5432'
volumes:
  postgres_data: